version: '3.5'

services:
  board:
    image: phashboard/board
    volumes:
      - static-assets-board:/var/www/html/public

  server:
    image: phashboard/server
    volumes:
      - static-assets-server:/var/www/html/public

  mongo:
    image: mongo:4

  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/complete.conf:/etc/nginx/conf.d/default.conf
      - static-assets-board:/var/www/html/board
      - static-assets-server:/var/www/html/server

volumes:
  static-assets-board:
  static-assets-server:
