version: '3.5'

services:
  board:
    image: phashboard/board:1
    volumes:
      - static-assets-board:/var/www/html/public

  server:
    image: phashboard/server:1
    volumes:
      - static-assets-server:/var/www/html/public

  mongo:
    image: mongo:4

  nginx:
    image: phashboard/nginx:1
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - static-assets-board:/var/www/html/board
      - static-assets-server:/var/www/html/server

volumes:
  static-assets-board:
  static-assets-server:
