version: '3.5'

services:
  board:
    image: phashboard
    environment:
      PUBLIC_WEBSOCKET_URL: ws://nginx/websocket

  server:
    image: phashserver

  nginx:
    image: phashnginx

  mongo:
    logging:
      driver: none

  chrome:
    image: yukinying/chrome-headless-browser:74.0.3729.28
    shm_size: 1024m
    cap_add:
      - SYS_ADMIN
    logging:
      driver: none

  tests:
    image: phashtests
    command: ${SCENARIO}
    depends_on:
      - chrome
      - board
      - server
      - nginx
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
